#!/usr/bin/env python3
"""Maintain an explicit Git-tracked allowlist for the source distribution."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

HEADER = (
    "# Generated by scripts/sync_sdist_manifest.py.\n"
    "# Only Git-tracked files may enter the source distribution.\n"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when MANIFEST.in is stale",
    )
    return parser.parse_args()


def git_tracked_files(root: Path) -> list[str] | None:
    completed = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=root,
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        return None
    paths = completed.stdout.decode("utf-8").split("\0")
    return sorted(path for path in paths if path and (root / path).is_file())


def manifest_entries(text: str) -> list[str]:
    entries: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not stripped.startswith("include "):
            raise ValueError(f"Unsupported MANIFEST.in directive: {stripped}")
        entries.append(stripped.removeprefix("include "))
    return entries


def render(paths: list[str]) -> str:
    return HEADER + "".join(f"include {path}\n" for path in paths)


def main() -> int:
    args = parse_args()
    root = Path(__file__).resolve().parents[1]
    manifest = root / "MANIFEST.in"
    tracked = git_tracked_files(root)
    if tracked is not None:
        expected = render(tracked)
        if args.check:
            if not manifest.is_file() or manifest.read_text(encoding="utf-8") != expected:
                raise SystemExit(
                    "MANIFEST.in is stale; stage intended files and run "
                    "scripts/sync_sdist_manifest.py"
                )
        else:
            manifest.write_text(expected, encoding="utf-8")
    else:
        if not manifest.is_file():
            raise SystemExit("MANIFEST.in is missing")
        entries = manifest_entries(manifest.read_text(encoding="utf-8"))
        if entries != sorted(set(entries)):
            raise SystemExit("MANIFEST.in entries must be sorted and unique")
        missing = [path for path in entries if not (root / path).is_file()]
        if missing:
            raise SystemExit(f"MANIFEST.in references missing files: {missing}")
    print("source-distribution manifest is an exact tracked-file allowlist")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
